
// export const EDITPHONE = 'EDITPHONE';
// export const EDITWEIXIN ='EDITWEIXIN';
// export const EDITREMARK ='EDITREMARK';

export const FETCH_USERS_INFO = 'FETCH_USERS_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';

export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_CLASS_INFO = 'GET_CLASS_INFO';

export const userMID = 'MID330900002';

export const MID_SEARCH = 'MID_SEARCH';
export const GET_SATISFILED_LIST = 'GET_SATISFILED_LIST';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CHANGE_REPLY_STATUS = 'CHANGE_REPLY_STATUS';

export const GET_HOME_WORK = 'GET_HOME_WORK';
export const GET_HOME_WORK_HAS_REVIEWED = 'GET_HOME_WORK_HAS_REVIEWED';
export const GET_ALL_HOME_WORK = 'GET_ALL_HOME_WORK';
export const GET_ALL_HOME_WORK_HAS_REVIEWED = 'GET_ALL_HOME_WORK_HAS_REVIEWED';

export const RETURN_COMMENT = 'RETURN_COMMENT';//退回评论

export const INPUT_NEW_COMMENT = "INPUT_NEW_COMMENT";//输入新的评论

export const TOGGLE_EXCELLENT = "TOGGLE_EXCELLENT";//更改佳作

export const GET_TEACHERS_RIGHT = "GET_TEACHERS_RIGHT";//获得老师的信息

export const GET_TEACHERS_LEFT = "GET_TEACHERS_LEFT";//获得左边老师的信息

export const ADD_TEACHERS_LEFT = "ADD_TEACHER_LEFT";//增加左边的老师

export const DELETE_TEACHER_LEFT = "DELETE_TEACHER_LEFT";//减少左边的老师

export const SEARCH_TEACHER_NAME_LEFT = "SEARCH_TEACHER_NAME_LEFT"//在左边框中搜索老师的名字

